package ClientServer;

public enum InquiryManagerActions {
    ALL_INQUIRY,
    ADD_INQUIRY,
    GET_INQUIRY_STATUS,
    CANCEL_INQUIRY,
    ADD_REPRESENTATIVE,
    DELETE_REPRESENTATIVE,
    IS_REPRESENTATIVE_ACTIVE,
    GET_REPRESENTATIVE_INQUIRIES,
    GET_REPRESENTATIVE_NAME_BY_INQUIRY_CODE,
    GET_ACTIVE_REPRESENTATIVES
}
